# Generated by Django 6.0.5 on 2026-05-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_allergen_loyaltyprogram_product_size_topping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="diet_info",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("halal", "Halal"),
                    ("gluten_free", "Gluten Free"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
